//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecommerce1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public int PacketId { get; set; }
        public string BusinessId { get; set; }
        public System.DateTime TokenDT { get; set; }
    
        public virtual Business Business { get; set; }
    }
}
